### PR TITLE
Wipe all semicolons and improve some logic

### PR DESCRIPTION
**Pull request by guitared**
semicolon is like 🐸

### CODE REVIEW

**Comment by thananon** [comment]
really? a PR to remove semicolon? NO.

**Comment by thananon** [comment]
The logic improvement looks ok to me. I have two problems:
- Is there a significant reason in our application to use `===` instead of `==`? (please justify)
- Using semicolon is my personal preference (of being a C coder). It helps me keep my sanity (non-negotiable. please undo semicolon removals).

**Comment by guitared** [comment]
Noted. 

For '==='; just want to avoid type coercion for string comparison. However, it's just a cosmetic.

Will revise the PR.

**Comment by guitared** [comment]
Moved to PR   #9

**Pull request closed without merging**
