### PR TITLE
add webapp for display GIF

### PR DESCRIPTION
**Pull request by theeradech-d**
webapp for management widget like a streamlab (#5)

run example
```shell
node webapp/example.js
```
open http://localhost:3000

example integrate with `9armbot.js`
```javascript
const webapp = require("../webapp");
//show GIF
webapp.socket.io().emit("widget::gif")
//show GIF and Text
webapp.socket.io().emit("widget::gif", {
    message: "Hello"
})
```

### CODE REVIEW

**Comment by thananon** [comment]
Oh wow. Thank you for this. Currently we have PR #10 and #17 to display GIF using socket.io. We will have to discuss how we move forward with this.

**Comment by thananon** [comment]
Oh wow. Nice work! I am in favor of this PR over #10 as it has a lot of feature. Let me dig into it for a couple more hours.

**Comment by thananon** [comment]
I really like it. I am still learning how to use this properly. 
- Do I have to create new directory in `widget` for new widget type? It seems like if I want two gifs for two different events, I have to create a new one.
- If so, when I create new widget, it has different target web interface (ie, `http://192.168.1.234:3000/widget/[widget name]`). Can we make it the same page?

This is more like a question. I am approving this PR but will wait for your response.

**Review by thananon — APPROVED** [review]

**Comment by theeradech-d** [comment]
you can copy `gif` directory for create new widget in `widgets` directory 

## New Widget
- copy `gif` directory
- change directory name
- change name, color in `widget.json`
- change Test function in `config.ejs`
```javascript
function Test() {
    socket.emit('widget', {
        id: "[widget name]",  //<------ change id to same name of widget directory
        message: $("#message").val()
    });
}
```
- delete `storage.json`  for clear old data 
- restart nodejs (default data in `widget.json` will save on `storage.json`)
- see widget in http://localhost:3000/widgets

## Widget Structure
    [widget name]
        ├── public                  # You can access file in http://localhost:3000/upload/widgets/[widget name]/[file name]
        ├── views                      
        │     ├── config.ejs        # Config form display at http://localhost:3000/widgets/[widget name]
        │     └── show.ejs          # Widget Frontend display at http://localhost:3000/widget/[widget name]
        ├── storage.json            # Every thing in config form (config.ejs) will save in this file
        └── widget.json             # Widget name, color, default storage data, public_path

## config.ejs
[view ejs template doc](https://ejs.co/#docs)
[view AdminLTE3 demo](https://adminlte.io/themes/v3/pages/forms/general.html)
for create Test Button and Config Form

you can get `widget` variable like this
```html
<%= widget.name %>
```
`storage` variable
```html
<%= widget.storage.alert_delay %>
<%= widget.storage.gif %>
<%= widget.storage.sound %>
```
example Test Button
```javascript
function Test() {
      socket.emit('widget', {
          id: "[widget name]",
          message: $("#message").val()
          // you can add other parameter 
      });
}
```
### Custom config property 
you can add input in `<form>`
example
```html
<form method="post" enctype="multipart/form-data">
<!-- default input -->

<!-- custom input text -->
<input type="text" class="form-control" id="message_template" name="message_template" value="<%= widget.storage.message_template%>">

<!-- custom input file-->
<input type="file" class="custom-file-input" id="keyword_file" name="keyword_file">

<!-- submit button-->
 <button type="submit" class="btn btn-primary">Save Setting</button>
</form>
```
when you `submit` all input in `<form>` will save on `storage.json`

## show.ejs
[view ejs template doc](https://ejs.co/#docs)
for display widget
```html
<!-- load socket io -->
<script src="https://cdn.socket.io/3.1.1/socket.io.min.js"></script>

<script>
//connect to socket io
var socket = io();

//show widget
socket.on('widget::<%= widget.id %>', (data) => {

    // set text and show widget
    $("#text").text(data.message)
    $("#widget").show()
    audio.play();

   //hide widget
   var time = <%= parseInt(storage.alert_delay)*1000 %>;
   setTimeout(function(){
        $("#widget").hide()
   }, time)
});

//reload this page when save config
socket.on('widget::<%= widget.id %>:reload', () => {
    window.location.reload()
});

</script>

<body>

<audio id="audio" src="/upload/widgets/<%= widget.id %>/<%= widget.storage.sound %>"></audio>
<div id="widget" style="display:none">
   <img src="/upload/widgets/<%= widget.id %>/<%= widget.storage.gif %>">
   <div id="text"></div>
</div>

</body>
```

**Comment by thananon** [comment]
Thank you for detailed answer. I still have the same question:
- Let's say I have 3 widgets (a, b and c).
  - If I understand correctly, these 3 widgets will show up in different page (`http://localhost:3000/widget/a` , `http://localhost:3000/widget/b` and `http://localhost:3000/widget/c`. 
  - It will be more ideal if we can display them at the same target page (something like `http://localhost:3000/widget/alerts`. So I only have to open one page. I might have missed this part in your explanation, please let me know.

- This is more like a feature request but can we have the option to upload file (gif/sound) to the server? (I am not running it locally) @rayriffy if you want to help (not priority, I might be able to figure this out myself).

**Pull request merged**
