### PR TITLE
feat(9armbot): media player

### LINKED ISSUE #5: A front page to display GIF.
We want to display GIF on screen when some event happen in our bot. Similar to what twitchalert has. Especially when someone wins big in `!gacha`.

### PR DESCRIPTION
**Pull request by rayriffy**
## Description

This PR fixes #5 

In this PR, when 9armbot is initiated, it will also create a websocket server at port 8085 (`ws://localhost:8085`). Then, any event that wants media to be played can be send via event with **proper payload** (you won't have any type issues if you use TypeScript so pls, refactor pls). All of this is handled by `sendSocketPayload` function

After that, web client will connect to websocket server, listen for an event and play the media.

I am not a streamer and I don't have proper tools for testing this feature yet. So, please review and gave feedback for changes pls.

### CODE REVIEW

**Comment by rayriffy** [comment]
A lot of improvements can be made
- Split functions into files, so it can get less messy.
- Use TypeScript to prevent type error in the first place.
- Change project structure to monorepo in order to support multiple projects and dependencies can be used as it's own indiviual without intervention (Larna, or Yarn worksapces but I reccomended Yarn workspaces)

**Comment by thananon** [comment]
The more I use JS the more I hate it. You keep pulling and pulling new bloat packages. yuck.
Ok, so tell me how do I test this? I can do `node ./9armbot.js` and thats good but how do I run the webserver? Do I actually have to do it on my own or there is some script I should run?

**Comment by rayriffy** [comment]
OK this refactor should do it, most of bloats deps are from `parcel-bundler` I quite like to use when I working on highly optimized site ([miko](https://github.com/rayriffy/miko) etc.). So, I refactor everything back to basic, serve only static files.

When `9armbot.js` is initialized and WebSocket is ready to send data, the message `Web socket is ready to emit data from port 8085!` should appear. I assigned this port to emit events data between web client and server, it should not being used by anyone (I guess).

To start web interface, run `npm run start:web` then you be good to go. Web interface will be available at port `http://localhost:1234`.

To emit event data, I already prepared `sendSocketPayload` function into `9armbot` it require 4 following parameters to operate.
- `type` - specify type of media `image` or `video`
- `source` - source of media, it can be url or base64 data
- `size` - is an object specifying size of media to display in pixels `{ width: number }` will set height to `auto`, `{ width: number, height: number }` will set width and height to fixed size.
- `position` - is an object to specify the pixel location to display a media `{ x: number, y: number }` by `x:0 y:0` the the top-left corner of the `window.document`.

I've made a demo to test that socket is acually works by implementing just a mock-up server [here](https://youtu.be/9mbeTFOdlBU).

**Comment by thananon** [comment]
omg. I didn't expect you to refactor parcel out. I was just being คนแก่ขี้บ่น. 

>  You keep pulling and pulling new bloat packages. yuck.

I meant JS in general, not you. Sorry, I shouldn't use those words.

Thank you so much for such detailed instructions. I am testing this tonight.

**Comment by thananon** [comment]
I must be doing something wrong. When I do `npm run start:web` I got a webpage that changes from `awaiting for connection` to `Crash! Look for stacktrace in DevTools`. It seems to be a connection error event in `socket.js`. I wonder what happened.

image

9armbot.js is doing what it should do:
```
Web socket is ready to emit data from port 8085!
[06:54] info: Connecting to irc-ws.chat.twitch.tv on port 443..
[06:54] info: Sending authentication to server..
[06:54] info: Connected to server.
Bot data restored...
[06:54] info: Executing command: JOIN #armzi
[06:54] info: Joined #armzi
```

Maybe there is something I should setup beforehand?
Also, I merged a couple PR, so can you rebase this on top of `main`?

**Comment by rayriffy** [comment]
Can I have a sample of sendSocketPayload and an error datails on Chrome Dev Tools pls?

**Comment by rayriffy** [comment]
9armbot seems to be functional but the client itself is not, maybe incorrect structure of payload causes it

**Comment by rayriffy** [comment]
Sry to spam comments but I want to debug everything to be done in first place.
I wonder that 9armbot might open port 8085 but did not actually send any data as well. Maybe try `curl "http://localhost:8085/socket.io/?EIO=4&transport=polling"` to test it as well

**Comment by thananon** [comment]
I haven't done anything other than running webserver and 9armbot. There is no payload yet. 

I got connection refused.
```
GET http://localhost:8085/socket.io/?EIO=4&transport=polling&t=NUZSgCm net::ERR_CONNECTION_REFUSED
```
So does this mean socket io failed to create socket?

**Comment by thananon** [comment]
Might be my rpi firewall settings.

**Comment by rayriffy** [comment]
So, it's not invalid payload that crash them but client cannot establish connection to socket server. Could be firewall please check? inb4 the behavior that I am having is when I `curl` to that address it will stuck with empty response all the time. Usually `9armbot` should open socket port first before open client in launcher.

I just tried to run `9armbot` with all of `tmi.js` functionality commented.

Screen Shot 2021-02-15 at 11 51 13

Socket server is running just fine, and also get response back, this might indicate that your firewall could be an issue??? (I guess dunno, I always living on the edge)

| | |
| - | - |
| Screen Shot 2021-02-15 at 11 49 56 | Screen Shot 2021-02-15 at 11 52 16 |

**Comment by thananon** [comment]
ok, I got it working. It seems like `socket.js` is a client-side script and it is doing:
```js
const armbotSocket = io('ws://localhost:8085')
```

This will fail when I open the website from another machine. (The bot is running on raspberry-pi, but I will have to connect to the website from my computer). Once I change `localhost` to my raspberry-pi address, it works.

Can we have an env to set server address?

**Comment by rayriffy** [comment]
Ah, I see. I thought you run everything on local machine at once. Now you should be able to set variable `SOCKET_ADDRESS` as an full address like `10.2.50.41:1458` (without specifying it will be `localhost:8085` by default)

**Comment by thananon** [comment]
Thank you for addressing the issue. However, now there is PR #17 which I think has better structure. What do you think? Can we extend that one instead?

**Comment by rayriffy** [comment]
Yes, it possible but I think those performance cost will be higher than this one for just to send a simple payload to display some media, but this PR can send payload to play video format instead as well. It's up to your decisions.

**Comment by rayriffy** [comment]
The reason I build an extra payload to display video becuase with same media loop, optimized mp4 can be served faster than gif with much more color available. So, it would be possible for less chance that gif media will hang up while loading and never get fully played.

**Comment by thananon** [comment]
I decided to go with PR #17 as it has web interface which will be easier to expand on later. I'm really sad as I quite like this PR. I hope we can port part of this PR in later.

I am inviting you to this project. Hopefully you will join.

**Pull request closed without merging**
